### ISSUE TITLE
Request: Add label size

### ISSUE THREAD

**Issue by pechex** [roelkneepkens/labelary-extension#3]
Hi!

I'm currently using ZPL Designer to design some lables. In that program you can set the label size, but I can't do it in your extension. It would be a great addition!

![image](https://user-images.githubusercontent.com/1761631/170305235-99488c8d-20b5-4375-9ab8-36b481e7a85a.png)
![image](https://user-images.githubusercontent.com/1761631/170305342-8cbea835-0e37-4a0e-b003-17c989f1ed0f.png)

**Comment by bvanderhorn** [comment]
> Hi!
> 
> I'm currently using ZPL Designer to design some lables. In that program you can set the label size, but I can't do it in your extension. It would be a great addition!
> 
> ![image](https://user-images.githubusercontent.com/1761631/170305235-99488c8d-20b5-4375-9ab8-36b481e7a85a.png) ![image](https://user-images.githubusercontent.com/1761631/170305342-8cbea835-0e37-4a0e-b003-17c989f1ed0f.png)

Hi @pechex , we fixed this in v1.0.6 (out now). We added some much-used sizes, and allow you to add your own custom sizes in a setting. Please check the readme!

**Comment by pechex** [comment]
Wow @bvanderhorn this is great! Thanks for this! It works perfectly.

Just one comment: You added one size called ELEA (I think after my screenshot above). But that's only how I named my custom size in ZPL Designer. It's the name of my client, not the actual name of thar paper size (not sure of the real name).
